services:
  quotewisp:
    image: maizihk/quotewisp:1.0.0-rc.5
    container_name: quotewisp
    restart: unless-stopped
    stop_grace_period: 15s
    user: "65532:65532"
    env_file:
      - path: ./.env
        format: raw
    ports:
      - "18080:8080"
    volumes:
      - ./data:/var/lib/quotewisp
    networks:
      - onepanel-network

networks:
  onepanel-network:
    name: 1panel-network
    external: true
