CREATE TABLE site_settings (
 id TINYINT UNSIGNED NOT NULL,
 site_name VARCHAR(64) NOT NULL,
 contact VARCHAR(256) NOT NULL,
 public_origin VARCHAR(512) NULL,
 repo_url VARCHAR(512) NULL,
 beian_text VARCHAR(128) NULL,
 beian_url VARCHAR(512) NULL,
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
