CREATE TABLE categories (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, code VARCHAR(32) COLLATE utf8mb4_bin NOT NULL,
 name VARCHAR(64) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, sort_order INT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY (id), UNIQUE KEY uk_categories_code (code), KEY idx_categories_enabled_sort (enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sentences (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, uuid CHAR(36) COLLATE utf8mb4_bin NOT NULL, category_id BIGINT UNSIGNED NOT NULL,
 content TEXT NOT NULL, source VARCHAR(255) NULL, author VARCHAR(128) NULL, length SMALLINT UNSIGNED NOT NULL,
 status TINYINT UNSIGNED NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), published_at DATETIME(6) NULL,
 PRIMARY KEY (id), UNIQUE KEY uk_sentences_uuid (uuid), KEY idx_sentences_publish_query (status, category_id, length, id),
 CONSTRAINT fk_sentences_category FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE dataset_versions (
 id TINYINT UNSIGNED NOT NULL, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 published_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO dataset_versions (id, version) VALUES (1, 1);
